site_name: Synthax
site_description: A JAX experiment

nav:
  - Index: index.md
  - Introduction: introduction.md
  - Source-Code: sourceCode.md
  - Process: process.md
  - Conclusion: conclusion.md

theme:
  name: material
  hide_site_name: true
  logo: assets/logo/syx-1.png
  favicon: assets/logo/syx-1.png
  site_url: "https://udit-rawat.github.io/Synthax"

  language: en
  font:
    text: Robo
    code: Robo sans
  palette:
    - scheme: default
      primary: light green
      accent: light green
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  plugins:
    - social
    - search
    - glightbox

  nav:
    - index
    - introduction
    - sourceCode
    - process
    - conclusion
  features:
    - tabs
    - search
    - navigation.tabs
    - navigation.expand
    - navigation.collapsible
    - navigation.top
    - palette
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - search.suggest
    - search.highlight
    - navigation.footer
    - content.code.copy

extra:
  homepage: /
  generator: false
  copy_code:
    button_text: "Copy"
    tooltip_text: "Copy to clipboard"
    success_text: "Copied!"
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/udit-rawat
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/udit-rawat-65204a279/
    - icon: fontawesome/brands/google
      link: mailto:uditrawat1905@gmail.com

  styles:
    - |
      .codehilite .hll {
        background-color: #ffeeba;
      }
      .codehilite {
        background: #f8f9fa;
        border: 1px solid #d6d8db;
        border-radius: 4px;
        margin: 0;
        padding: 1em;
        position: relative;
      }
      .codehilite .lang-label {
        position: absolute;
        top: 0.25em;
        right: 0.25em;
        background-color: #343a40;
        color: #ffffff;
        padding: 0.2em 0.5em;
        font-size: 0.8em;
        border-radius: 4px;
      }
  footer: |
    <div style="text-align: center; margin-top: 20px;">
      <a target="_blank" href="https://icons8.com/icon/5KGHGfq5i7DU/tangent">Maths</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>
    </div>
markdown_extensions:
  - admonition
  - attr_list
  - tables
  - pymdownx.arithmatex:
      generic: true
  - md_in_html
  - pymdownx.mark
  - pymdownx.extra
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
      auto_title: true
      anchor_linenums: true
      linenums: true
      line_spans: __span
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: Copyright &copy; 2024-25 Udit Rawat
